title: Max Tagher
description: "Personal blog of Max Tagher"
permalink: /:title/
lsi: false
markdown: redcarpet

author :
  name : Max Tagher
  email : feedback.tagher@gmail.com
  github : maxgabriel
  twitter : MaxTagher